package prompts

import (
	"fmt"
	"sort"
	"strings"

	"github.com/example/wikiforge/internal/model"
)

func page(path, objective, diagram, table string, headings ...string) model.PageContract {
	return model.PageContract{Path: path, Objective: objective, RequiredDiagram: diagram, RequiredTableHeader: table, RequiredHeadings: headings}
}

var applicationSupplementalPages = []model.PageContract{
	page("configuration/runtime-configuration.md", "Catalog application properties, environment variables, secret references, and external configuration sources as one precedence-aware runtime configuration model.", "flowchart", "| Configuration Key | Kind | Source | Default | Required | Sensitive | Runtime Behaviour | Consumer | Evidence |", "Configuration Model", "Application Properties", "Environment Variables", "Secret References", "External Configuration Sources", "Precedence and Resolution", "Validation and Failure Behaviour", "Runtime Reload and Restart Behaviour", "Consumer Map", "Security and Redaction", "Configuration Catalog", "Knowledge Gaps", "Source References"),
	page("integrations/service-to-service.md", "Document verified internal component-to-component communication, including protocol, contract, identity, resilience, and failure impact.", "sequenceDiagram", "| Caller | Callee | Protocol | Contract | Authentication | Timeout | Retry | Criticality | Evidence |", "Communication Inventory", "Inbound Internal Calls", "Outbound Internal Calls", "Protocols and Contracts", "Authentication and Identity Propagation", "Timeouts Retries and Fallbacks", "Idempotency and Duplicate Handling", "Failure Impact", "Observability and Correlation", "Communication Catalog", "Knowledge Gaps", "Source References"),
	page("integrations/external-services.md", "Document communication with external parties, vendors, SaaS products, identity providers, payment providers, government systems, and partner services.", "sequenceDiagram", "| External Party | Direction | Protocol | Contract | Data Exchanged | Authentication | Limit or SLA | Failure Handling | Evidence |", "External Dependency Inventory", "Inbound External Communication", "Outbound External Communication", "Data Exchanged and Classification", "Authentication and Trust", "Limits Quotas and Service Expectations", "Timeout Retry and Reconciliation", "Outage and Degraded Behaviour", "Test and Sandbox Evidence", "External Service Catalog", "Knowledge Gaps", "Source References"),
	page("integrations/cloud-services.md", "Catalog dependencies on managed cloud services and explain identity, region, quota, availability, cost, and recovery implications.", "flowchart", "| Provider | Service | Resource Reference | Purpose | Region or Account | Identity | Data | Quota | Failure Impact | Evidence |", "Cloud Dependency Inventory", "Providers Accounts and Regions", "Managed Compute and Runtime", "Managed Data and Storage", "Messaging and Integration Services", "Identity Secrets and Key Services", "Observability and Operations Services", "Quotas Capacity and Cost Drivers", "Availability Backup and Recovery", "Cloud Service Catalog", "Knowledge Gaps", "Source References"),
	page("integrations/dependency-matrix.md", "Provide a component-level dependency matrix covering internal components, external parties, cloud services, libraries, configuration, contracts, and infrastructure.", "flowchart", "| Source | Dependency | Relationship | Protocol or Mechanism | Criticality | Failure Impact | Owner Evidence | Source Evidence |", "Dependency Scope", "Runtime Dependencies", "Build and Library Dependencies", "Configuration and Contract Dependencies", "Infrastructure and Cloud Dependencies", "Optional and Conditional Dependencies", "Criticality and Failure Impact", "Cycles and Hidden Coupling", "Dependency Matrix", "Knowledge Gaps", "Source References"),
	page("interfaces/endpoint-catalog.md", "Catalog every evidence-backed endpoint across HTTP, REST, SOAP, GraphQL, RPC, gRPC, SFTP, FTP, TCP, UDP, WebSocket, SSE, file drop, and custom protocols.", "flowchart", "| Endpoint ID | Direction | Protocol | Address or Operation | Purpose | Caller or Provider | Authentication | Input | Output | Error Semantics | Evidence |", "Catalog Scope", "Inbound Endpoints", "Outbound Endpoints", "Synchronous Endpoints", "Streaming and Long-Lived Endpoints", "File Transfer and Drop Endpoints", "Authentication and Authorization", "Validation Errors and Retryability", "Versioning and Compatibility", "Endpoint Catalog", "Knowledge Gaps", "Source References"),
	page("messaging/event-catalog.md", "Catalog external and internal events, messages, queues, topics, subjects, exchanges, in-memory event buses, and local job queues.", "flowchart", "| Event ID | Event or Message | Transport | Channel | Producer | Consumer | Trigger | Delivery | Ordering | Retry or DLQ | Evidence |", "Catalog Scope", "External Broker Events", "Internal Application Events", "In-Memory Queues and Event Buses", "Producers and Consumers", "Payloads and Schemas", "Partitioning Routing and Ordering", "Delivery Retry and Dead Letter Behaviour", "Replay Idempotency and Transactions", "Event Catalog", "Knowledge Gaps", "Source References"),
	page("processing/job-catalog.md", "Catalog cron jobs, timers, polling loops, workers, batch jobs, queue jobs, delayed tasks, and maintenance operations.", "flowchart", "| Job ID | Type | Trigger or Schedule | Time Zone | Purpose | Concurrency | Locking | Retry | Timeout | Recovery | Evidence |", "Catalog Scope", "Scheduled Jobs", "Queue and Worker Jobs", "Polling and Timer Jobs", "Batch and Maintenance Jobs", "Concurrency Locking and Idempotency", "Retry Misfire and Catch-Up", "Timeout Cancellation and Shutdown", "Failure Detection and Recovery", "Job Catalog", "Knowledge Gaps", "Source References"),
	page("business/business-flows.md", "Document evidence-backed business flows, actors, preconditions, happy paths, alternatives, state transitions, side effects, failures, and compensation.", "sequenceDiagram", "| Flow ID | Flow | Trigger | Actors | Primary State Changes | External Calls | Events | Failure or Compensation | Evidence |", "Flow Inventory", "Actors and Preconditions", "Primary Business Flows", "Alternate and Exceptional Paths", "State Transitions", "Data Changes", "External Calls and Events", "Transactions Idempotency and Compensation", "Flow Change Risks", "Business Flow Catalog", "Knowledge Gaps", "Source References"),
	page("business/rules-and-validation.md", "Merge business rules and validation rules into one traceable catalog while distinguishing transport, schema, domain, authorization, external, and database validation.", "flowchart", "| Rule ID | Name | Category | Inputs | Condition or Constraint | Outcome or Error | Scope | Enforcement Point | Test Evidence | Source Evidence |", "Rule Scope", "Business Decision Rules", "Invariants", "Transport and Schema Validation", "Domain and Cross-Entity Validation", "Authorization Validation", "External and Database Validation", "Rule Ordering and Conflicts", "Error Semantics", "Rules and Validation Catalog", "Knowledge Gaps", "Source References"),
	page("business/business-data.md", "Describe business data concepts, identities, ownership, lifecycle, reference data, state, sensitivity, and relationships independently from physical storage.", "classDiagram", "| Business Concept | Identity | Owner | Lifecycle | Key Rules | Sensitive | Physical Representation | Evidence |", "Business Data Scope", "Core Concepts and Identities", "Ownership and Authority", "Lifecycle and State", "Reference and Master Data", "Relationships", "Sensitive and Regulated Data", "Derived and Historical Data", "Physical Mapping", "Business Data Catalog", "Knowledge Gaps", "Source References"),
	page("runtime/traffic-flows.md", "Document network traffic paths from external or internal entry points through DNS, edge controls, proxies, load balancers, gateways, sidecars, runtime listeners, and downstream network hops.", "sequenceDiagram", "| Flow ID | Entry Point | Network Hops | Protocol Transitions | Trust Boundaries | Routing or Load Balancing | Timeout or Retry | Failure Path | Evidence |", "Traffic Scope", "Traffic Entry Points", "Network Hops", "Protocol Transitions", "TLS and Trust Boundaries", "Routing Proxying and Load Balancing", "Header and Metadata Propagation", "Timeout Retry and Rate-Limit Boundaries", "Failure and Degraded Paths", "Traffic Flow Catalog", "Knowledge Gaps", "Source References"),
	page("runtime/request-flows.md", "Document internal request processing from trigger through filters, middleware, authentication, authorization, validation, application and domain logic, persistence, events, dependencies, and response mapping.", "sequenceDiagram", "| Flow ID | Trigger | Internal Stages | Security | Validation | Data Access | Dependencies or Events | Context | Error Path | Evidence |", "Request Flow Scope", "Request Entry and Dispatch", "Filters Middleware and Interceptors", "Authentication and Authorization Stages", "Validation and Normalization", "Application and Domain Processing", "Persistence Events and Outbound Calls", "Context Deadlines and Transactions", "Response Mapping and Error Paths", "Request Flow Catalog", "Knowledge Gaps", "Source References"),
	page("security/authentication.md", "Document how human, service, machine, batch, and external identities are established, validated, propagated, refreshed, expired, and rejected.", "sequenceDiagram", "| Identity or Actor | Mechanism | Credential or Token | Issuer or Source | Validation | Session or Lifecycle | Failure Behaviour | Evidence |", "Authentication Scope", "Identity Types and Sources", "Authentication Protocols", "Credentials Tokens and Certificates", "Issuer Audience Signature and Claim Validation", "Human Session and Token Lifecycle", "Service Workload and Machine Identity", "Authentication Context Propagation", "Logout Revocation Expiry and Rotation", "Authentication Catalog", "Knowledge Gaps", "Source References"),
	page("security/authorization.md", "Document authorization models, roles, permissions, claims, policies, ACLs, ownership rules, decision inputs, enforcement points, propagation, and deny behaviour.", "flowchart", "| Actor or Role | Resource or Operation | Authorization Model | Permission or Policy | Enforcement Point | Decision Inputs | Deny Behaviour | Evidence |", "Authorization Scope", "Authorization Models", "Roles Permissions Claims and Policies", "Protected Resources and Operations", "Decision Inputs and Context", "Enforcement Points", "Downstream Permission Propagation", "Administrative Delegated and Break-Glass Access", "Deny Failure and Audit Behaviour", "Authorization Matrix", "Knowledge Gaps", "Source References"),
	page("runtime/concurrency.md", "Document threads, executors, worker pools, event loops, schedulers, coroutines, locks, shared mutable state, ordering, race risks, blocking boundaries, and graceful shutdown.", "flowchart", "| Execution Unit | Threading Model | Pool or Scheduler | Concurrency | Shared State | Synchronization | Ordering | Shutdown | Evidence |", "Concurrency Scope", "Execution and Threading Model", "Thread Pools Executors Schedulers and Event Loops", "Shared Mutable State", "Synchronization Locks Atomics and Coordination", "Ordering and Visibility Guarantees", "Blocking Boundaries and Resource Exhaustion", "Deadlock Starvation and Race Risks", "Shutdown and Resource Cleanup", "Concurrency Catalog", "Knowledge Gaps", "Source References"),
	page("runtime/asynchronous-processing.md", "Document futures, promises, callbacks, reactive pipelines, coroutines, local queues, background tasks, detached work, backpressure, cancellation, durability, retry, and process-death behaviour.", "flowchart", "| Async Flow | Trigger | Mechanism | Queue or Scheduler | Ownership | Backpressure | Retry or Error | Cancellation | Durability | Evidence |", "Asynchronous Processing Scope", "Async Flow Inventory", "Futures Promises Callbacks and Coroutines", "Reactive Pipelines and Event Loops", "Local Queues Background Tasks and Detached Work", "Ownership Lifecycle and Durability", "Backpressure Queue Limits and Rejection", "Errors Retry Cancellation and Timeouts", "Shutdown Process Death and Recovery", "Asynchronous Processing Catalog", "Knowledge Gaps", "Source References"),
	page("runtime/context-propagation.md", "Document request, thread, trace, security, tenant, transaction, locale, deadline, logging, and business context propagation and cleanup.", "sequenceDiagram", "| Context | Created At | Stored As | Propagation Mechanism | Boundary | Consumer | Cleanup | Failure or Leak Risk | Evidence |", "Context Inventory", "Creation and Ownership", "Request and Thread Context", "Trace Correlation and Logging Context", "Security and Tenant Context", "Transaction and Persistence Context", "Deadlines Cancellation and Locale", "Process and Messaging Boundaries", "Cleanup and Leakage Risks", "Context Propagation Matrix", "Knowledge Gaps", "Source References"),
	page("data/database-structure.md", "Catalog databases, schemas, tables, collections, columns, keys, constraints, indexes, sequences, partitions, views, materialized views, synonyms, and links.", "erDiagram", "| Object | Type | Owner | Purpose | Keys or Constraints | Relationships | Sensitive | Lifecycle or Retention | Evidence |", "Database Scope", "Database and Schema Inventory", "Tables Collections and Fields", "Keys Constraints and Identifiers", "Indexes and Access Paths", "Sequences Identity and Key Generation", "Partitions Retention and Archival", "Views Materialized Views Synonyms and Links", "Ownership and Sensitive Data", "Database Structure Catalog", "Knowledge Gaps", "Source References"),
	page("data/database-programmability.md", "Merge database programmability and PL/SQL into one catalog of functions, procedures, packages, triggers, rules, stored jobs, cursors, dynamic SQL, and transaction behaviour.", "flowchart", "| Object | Type | Purpose | Inputs and Outputs | Reads | Writes | Called By | Transaction or Security Behaviour | Evidence |", "Programmable Object Scope", "Functions and Procedures", "Packages Modules and Types", "Triggers Rules and Notifications", "Stored Jobs and Schedulers", "Cursors Bulk Operations and Dynamic SQL", "Reads Writes and Side Effects", "Transactions Exceptions and Error Semantics", "Execution Rights Performance and Locking", "Database Programmability Catalog", "Knowledge Gaps", "Source References"),
	page("security/cryptography.md", "Document cryptographic use cases, algorithms, parameters, certificates, keys, trust stores, randomness, rotation, and unsafe implementations without exposing key material.", "flowchart", "| Use Case | Primitive or Protocol | Algorithm and Parameters | Key or Certificate Source | Rotation | Data Scope | Failure Behaviour | Risk | Evidence |", "Cryptographic Scope", "Encryption at Rest", "Encryption in Transit", "Hashing MACs and Password Protection", "Digital Signatures and Token Protection", "Certificates Trust Stores and TLS", "Key Generation Storage and Rotation", "Randomness Nonces IVs and Salts", "Deprecated or Dangerous Patterns", "Cryptography Catalog", "Knowledge Gaps", "Source References"),
	page("files/file-handling-and-formats.md", "Merge file handling and file formats into one catalog covering upload, download, SFTP, local disk, volumes, object storage, streaming, archives, validation, cleanup, retention, and security.", "flowchart", "| Flow or Format | Direction | Transport or Storage | Path or Pattern | Format | Size or Streaming | Validation | Retention or Cleanup | Security | Evidence |", "File Scope", "File Flow Inventory", "File Formats and Schemas", "Upload Download and Streaming", "SFTP FTP and File-Drop Processing", "Local Volumes Temporary Files and Object Storage", "Naming Checksums and Duplicate Handling", "Validation Parsing and Error Handling", "Security Atomicity Retention and Cleanup", "File Handling and Format Catalog", "Knowledge Gaps", "Source References"),
}

func selectedPages(paths ...string) []model.PageContract {
	wanted := map[string]bool{}
	for _, p := range paths {
		wanted[p] = true
	}
	var out []model.PageContract
	for _, p := range applicationSupplementalPages {
		if wanted[p.Path] {
			out = append(out, p)
		}
	}
	return out
}

func SupplementalPages(profileID string) []model.PageContract {
	switch profileID {
	case "application", "modular-application", "generic":
		return append([]model.PageContract(nil), applicationSupplementalPages...)
	case "reusable":
		return selectedPages(
			"configuration/runtime-configuration.md", "integrations/service-to-service.md", "integrations/external-services.md", "integrations/cloud-services.md", "integrations/dependency-matrix.md", "interfaces/endpoint-catalog.md", "messaging/event-catalog.md", "processing/job-catalog.md", "runtime/traffic-flows.md", "runtime/request-flows.md", "security/authentication.md", "security/authorization.md", "runtime/concurrency.md", "runtime/asynchronous-processing.md", "runtime/context-propagation.md", "data/database-structure.md", "data/database-programmability.md", "security/cryptography.md", "files/file-handling-and-formats.md",
		)
	case "infrastructure":
		return selectedPages(
			"configuration/runtime-configuration.md", "integrations/service-to-service.md", "integrations/external-services.md", "integrations/cloud-services.md", "integrations/dependency-matrix.md", "interfaces/endpoint-catalog.md", "messaging/event-catalog.md", "processing/job-catalog.md", "runtime/traffic-flows.md", "runtime/request-flows.md", "security/authentication.md", "security/authorization.md", "runtime/context-propagation.md", "security/cryptography.md", "files/file-handling-and-formats.md",
		)
	case "configuration":
		return selectedPages(
			"configuration/runtime-configuration.md", "integrations/external-services.md", "integrations/cloud-services.md", "integrations/dependency-matrix.md", "interfaces/endpoint-catalog.md", "processing/job-catalog.md", "security/authentication.md", "security/authorization.md", "runtime/context-propagation.md", "security/cryptography.md", "files/file-handling-and-formats.md",
		)
	case "contracts":
		return selectedPages(
			"integrations/service-to-service.md", "integrations/external-services.md", "integrations/dependency-matrix.md", "interfaces/endpoint-catalog.md", "messaging/event-catalog.md", "business/business-data.md", "security/authentication.md", "security/authorization.md", "security/cryptography.md", "files/file-handling-and-formats.md",
		)
	default:
		return nil
	}
}

var SystemSupplementalPages = []model.PageContract{
	page("system/dependency-matrix.md", "Aggregate component, external, cloud, library, configuration, contract, and infrastructure dependencies into a directionally correct system matrix.", "flowchart", "| Source Component | Dependency | Relationship | Protocol or Mechanism | Criticality | Failure Impact | Ownership Evidence | Source Documentation |", "Matrix Scope", "Runtime Dependencies", "Build Library and Framework Dependencies", "Configuration Contract and Schema Dependencies", "Infrastructure and Cloud Dependencies", "External Parties and Services", "Criticality and Failure Impact", "Cycles Hidden Coupling and Contradictions", "System Dependency Matrix", "Knowledge Gaps", "Source References"),
	page("system/endpoint-catalog.md", "Aggregate all endpoint types and interaction directions across the landscape.", "flowchart", "| Component | Endpoint ID | Direction | Protocol | Address or Operation | Counterparty | Authentication | Contract | Criticality | Source Documentation |", "Catalog Scope", "HTTP and API Endpoints", "RPC and gRPC Endpoints", "Streaming and Long-Lived Endpoints", "SFTP FTP and File Endpoints", "Custom and Infrastructure Endpoints", "Authentication Authorization and Trust", "Versioning Errors and Retryability", "System Endpoint Catalog", "Knowledge Gaps", "Source References"),
	page("system/event-catalog.md", "Aggregate brokered and in-memory events, messages, channels, producers, consumers, delivery semantics, replay, and recovery.", "flowchart", "| Producer | Event or Message | Transport | Channel | Consumer | Schema or Payload | Delivery | Ordering | Retry or DLQ | Source Documentation |", "Catalog Scope", "Kafka RabbitMQ NATS and Brokered Events", "Cloud Messaging", "Internal Application Events", "In-Memory Queues and Local Event Buses", "Producer and Consumer Topology", "Delivery Ordering Retry and Dead Letters", "Replay Idempotency and Transaction Boundaries", "System Event Catalog", "Knowledge Gaps", "Source References"),
	page("system/job-catalog.md", "Aggregate cron, scheduled, polling, batch, worker, queue, delayed, and maintenance jobs.", "flowchart", "| Component | Job ID | Type | Trigger or Schedule | Time Zone | Purpose | Concurrency or Lock | Retry or Recovery | Criticality | Source Documentation |", "Catalog Scope", "Scheduled and Cron Jobs", "Workers and Queue Jobs", "Polling Timer and Batch Jobs", "Maintenance and Infrastructure Jobs", "Concurrency Locking and Idempotency", "Retry Misfire Catch-Up and Recovery", "Operational Ownership and Alerts", "System Job Catalog", "Knowledge Gaps", "Source References"),
	page("system/business-flow-rules-and-data.md", "Aggregate business flows, rules, validation, business data ownership, and cross-component state transitions.", "sequenceDiagram", "| Flow or Rule | Owner Component | Trigger or Inputs | Outcome or State Change | Validation | Dependencies | Events | Evidence |", "Business Scope", "Critical Business Flows", "Cross-Component State Transitions", "Business Rules and Invariants", "Validation Boundaries", "Business Data Ownership", "Reference Master and Sensitive Data", "Failure Compensation and Reconciliation", "Business Flow Rule and Data Catalog", "Knowledge Gaps", "Source References"),
	page("system/traffic-flows.md", "Aggregate external and internal network traffic paths, edge controls, hops, protocol transitions, routing, load balancing, trust boundaries, timeout allocation, and failure paths.", "sequenceDiagram", "| Flow ID | Entry Point | Network Hops | Components | Protocol Transitions | Trust Boundaries | Routing or Load Balancing | Failure Path | Source Documentation |", "Traffic Scope", "External and Internal Entry Points", "DNS Edge Network and Trust Boundaries", "Routing Proxying and Load Balancing", "Protocol and TLS Transitions", "Service Mesh Sidecars and Gateways", "Header Metadata and Identity Transport", "Timeout Retry Rate-Limit and Failure Paths", "System Traffic Flow Catalog", "Knowledge Gaps", "Source References"),
	page("system/request-flows.md", "Aggregate request-processing paths across components from dispatch through security, validation, business logic, data access, events, dependencies, context, and response handling.", "sequenceDiagram", "| Flow ID | Trigger | Components and Internal Stages | Security | Validation | Data Access | Dependencies or Events | Context | Error Path | Source Documentation |", "Request Flow Scope", "Entry Dispatch and Routing", "Security Enforcement Stages", "Validation and Normalization", "Application Domain and Orchestration Stages", "Data Access Transactions and Caches", "Events Messages and External Dependencies", "Context Deadlines and Correlation", "Response Error Compensation and Degraded Paths", "System Request Flow Catalog", "Knowledge Gaps", "Source References"),
	page("system/authentication.md", "Aggregate human, service, workload, machine, batch, partner, and cloud authentication mechanisms, identity issuers, credentials, lifecycle, propagation, and failure behaviour.", "sequenceDiagram", "| Identity or Actor | Authentication Mechanism | Credential or Token | Issuer or Source | Validation Components | Lifecycle or Rotation | Failure Behaviour | Source Documentation |", "Authentication Scope", "Identity Domains and Sources", "Human Authentication", "Service Workload and Machine Authentication", "Partner and External Authentication", "Cloud and Infrastructure Identity", "Credential Token Certificate and Session Lifecycle", "Authentication Propagation and Trust Boundaries", "Revocation Expiry Rotation and Failure", "System Authentication Catalog", "Knowledge Gaps", "Source References"),
	page("system/authorization.md", "Aggregate authorization models, roles, permissions, claims, policies, ownership, enforcement components, propagation, administrative access, and audit behaviour.", "flowchart", "| Actor or Role | Protected Resource or Operation | Authorization Model | Permission or Policy | Enforcement Components | Decision Inputs | Deny or Audit Behaviour | Source Documentation |", "Authorization Scope", "Authorization Models", "Roles Permissions Claims Policies and ACLs", "Protected Resources and Operations", "Decision Inputs Tenant and Ownership Context", "Enforcement Components", "Cross-Component Authorization Propagation", "Administrative Delegated and Break-Glass Access", "Deny Failure and Audit Behaviour", "System Authorization Matrix", "Knowledge Gaps", "Source References"),
	page("system/concurrency.md", "Aggregate component threading models, pools, schedulers, shared state, synchronization, ordering, blocking boundaries, shutdown, and systemic concurrency risks.", "flowchart", "| Component | Threading Model | Pool or Scheduler | Concurrency | Shared State | Synchronization | Ordering | Shutdown | Risk | Source Documentation |", "Concurrency Scope", "Execution Model Inventory", "Thread Pools Executors Schedulers and Event Loops", "Shared Mutable State and Ownership", "Synchronization Locks Atomics and Coordination", "Ordering Visibility and Partitioning", "Blocking Boundaries and Resource Exhaustion", "Deadlock Starvation Race and Shutdown Risks", "System Concurrency Matrix", "Knowledge Gaps", "Source References"),
	page("system/asynchronous-processing.md", "Aggregate asynchronous work across futures, callbacks, reactive pipelines, local and broker queues, background tasks, ownership, durability, backpressure, retry, cancellation, and recovery.", "flowchart", "| Component | Async Flow | Trigger | Mechanism | Queue or Scheduler | Ownership or Durability | Backpressure | Retry or Cancellation | Failure Impact | Source Documentation |", "Asynchronous Processing Scope", "Async Flow Inventory", "Futures Callbacks Coroutines and Reactive Pipelines", "Local Queues Background Jobs and Detached Work", "Broker and Process Boundaries", "Ownership Durability and Completion Semantics", "Backpressure Limits and Rejection", "Retry Cancellation Shutdown and Recovery", "System Asynchronous Processing Matrix", "Knowledge Gaps", "Source References"),
	page("system/context-propagation.md", "Aggregate request, thread, trace, logging, security, tenant, transaction, locale, deadline, and business context across thread, process, messaging, and network boundaries.", "sequenceDiagram", "| Context | Created By | Propagated Through | Boundary | Consumers | Cleanup | Loss or Leakage Risk | Source Documentation |", "Context Scope", "Context Inventory and Ownership", "Request Thread and Logging Context", "Trace Correlation and Baggage", "Security Tenant and Business Context", "Transaction Locale Deadline and Cancellation Context", "HTTP RPC Messaging and Async Propagation", "Cleanup Context Loss and Leakage Risks", "System Context Propagation Matrix", "Knowledge Gaps", "Source References"),
	page("system/database-structures-and-programmability.md", "Aggregate database ownership, structures, programmable objects, PL/SQL or equivalent stored code, transaction behaviour, and coupling.", "erDiagram", "| Component | Database or Schema | Object | Type | Owner | Reads or Writes | Called By | Transaction or Security Behaviour | Source Documentation |", "Database Landscape", "Database and Schema Ownership", "Tables Collections Views and Indexes", "Shared Structures and Coupling", "Functions Procedures Packages and Triggers", "Stored Jobs Rules and Notifications", "Transaction Locking and Execution Rights", "Migration Compatibility and Recovery", "System Database Structure and Programmability Catalog", "Knowledge Gaps", "Source References"),
	page("system/configuration-secrets-and-external-sources.md", "Aggregate application properties, environment variables, secret references, external configuration sources, precedence, consumers, and rollout dependencies.", "flowchart", "| Component | Configuration or Secret | Kind | Source | Consumer | Sensitive | Precedence or Reload | Deployment Dependency | Source Documentation |", "Configuration Landscape", "Application Properties and Environment Variables", "Secret References and Stores", "External Configuration Sources", "Precedence Overrides and Resolution", "Consumer and Ownership Map", "Reload Restart and Rollout Ordering", "Redaction Rotation and Failure Behaviour", "System Configuration and Secret Catalog", "Knowledge Gaps", "Source References"),
	page("system/cloud-service-dependencies.md", "Aggregate cloud provider and managed-service dependencies, account or region boundaries, identities, data, quotas, availability, cost, and recovery.", "flowchart", "| Component | Provider | Cloud Service | Resource Reference | Account or Region | Identity | Data | Quota or Cost Driver | Failure Impact | Source Documentation |", "Cloud Landscape", "Providers Accounts Subscriptions and Projects", "Managed Compute Data Storage and Messaging", "Identity Secret and Key Services", "Network Edge and Observability Services", "Data Classification and Residency", "Quotas Capacity and Cost Drivers", "Availability Backup and Recovery", "System Cloud Service Catalog", "Knowledge Gaps", "Source References"),
	page("system/cryptography-and-key-management.md", "Aggregate cryptographic primitives, protocols, certificates, keys, trust stores, ownership, rotation, and unsafe patterns.", "flowchart", "| Component | Use Case | Primitive or Protocol | Algorithm or Parameters | Key or Certificate Source | Owner | Rotation | Risk | Source Documentation |", "Cryptographic Landscape", "Encryption in Transit", "Encryption at Rest", "Hashing MACs Passwords and Signatures", "Token and Message Protection", "Certificates Trust Stores and Mutual TLS", "Key Stores KMS HSM and Rotation", "Randomness Parameters and Deprecated Patterns", "System Cryptography and Key Management Catalog", "Knowledge Gaps", "Source References"),
	page("system/file-handling-and-formats.md", "Aggregate file exchange, SFTP, uploads, downloads, object storage, local volumes, formats, validation, retention, cleanup, and security.", "flowchart", "| Source | Destination | Direction | Transport or Storage | Path or Pattern | Format | Size or Streaming | Validation | Retention or Security | Source Documentation |", "File Exchange Landscape", "SFTP FTP and Partner File Flows", "HTTP Upload and Download Flows", "Object Storage and Shared Volumes", "File Formats Schemas and Encodings", "Streaming Buffering and Size Limits", "Naming Checksums Duplicates and Atomicity", "Validation Quarantine Retention and Cleanup", "System File Handling and Format Catalog", "Knowledge Gaps", "Source References"),
}

func supplementalContractsText(pages []model.PageContract) string {
	var b strings.Builder
	for _, p := range pages {
		fmt.Fprintf(&b, "### openwiki/%s\nObjective: %s\nRequired sections:\n", p.Path, p.Objective)
		for _, h := range p.RequiredHeadings {
			fmt.Fprintf(&b, "- ## %s\n", h)
		}
		fmt.Fprintf(&b, "Diagram: %s\n", diagramContract(p.RequiredDiagram))
		if p.RequiredTableHeader != "" {
			fmt.Fprintf(&b, "Required catalog header: `%s`\n", p.RequiredTableHeader)
		}
		b.WriteString("\n")
	}
	return strings.TrimSpace(b.String())
}

func SupplementalContractsText(profileID string) string {
	return supplementalContractsText(SupplementalPages(profileID))
}

func SystemSupplementalContractsText() string {
	return supplementalContractsText(SystemSupplementalPages)
}

func pageContractMap(phases []model.Phase, supplemental []model.PageContract) map[string]model.PageContract {
	out := map[string]model.PageContract{}
	for _, p := range phases {
		if p.OutputFile == "" {
			continue
		}
		out[p.OutputFile] = model.PageContract{Path: p.OutputFile, Objective: p.Objective, RequiredHeadings: p.RequiredHeadings, RequiredDiagram: p.RequiredDiagram}
	}
	for _, p := range supplemental {
		out[p.Path] = p
	}
	return out
}

func ComponentPageContracts(profile Profile) map[string]model.PageContract {
	return pageContractMap(profile.Phases, SupplementalPages(profile.ID))
}

func SystemPageContracts() map[string]model.PageContract {
	return pageContractMap(SystemPhases, SystemSupplementalPages)
}

func sortedContractPaths(contracts map[string]model.PageContract) []string {
	paths := make([]string, 0, len(contracts))
	for path := range contracts {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}
